# Generated by Django 3.2.4 on 2021-06-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("API", "0001_initial"),
        ("API", "0002_apiuser_email"),
        ("API", "0003_auto_20210625_0207"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIUserKey",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("prefix", models.CharField(editable=False, max_length=8, unique=True)),
                ("hashed_key", models.CharField(editable=False, max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="A free-form name for the API key. Need not be unique. 50 characters max.",
                        max_length=50,
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Once API key expires, clients cannot use it anymore.",
                        null=True,
                        verbose_name="Expires",
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True)),
                (
                    "username",
                    models.CharField(
                        default="devuser", max_length=512, verbose_name="API User Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "API key",
                "verbose_name_plural": "API keys",
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
    ]
