# Generated by Django 3.2 on 2023-09-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0001_initial_squashed_0003_auto_20210625_0207"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiuserkey",
            name="can_create_key",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="apiuserkey",
            name="hashed_key",
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name="apiuserkey",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=150,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="apiuserkey",
            name="username",
            field=models.CharField(max_length=512, verbose_name="API User Name"),
        ),
    ]
