# Generated by Django 3.2.4 on 2021-06-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiuser",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
