# Generated by Django 3.2.4 on 2021-06-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0002_apiuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiuserkey",
            name="apiuser",
        ),
        migrations.AddField(
            model_name="apiuserkey",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="apiuserkey",
            name="username",
            field=models.CharField(
                default="devuser", max_length=512, verbose_name="API User Name"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="APIUser",
        ),
    ]
