"""
Django settings for pvapi project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import environ
from corsheaders.defaults import default_headers

from pvapi.settings.databases import DATABASES, ELASTICSEARCH  # noqa

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Django configuration
SECRET_KEY = env("DJANGO_SECRET_KEY")
DEBUG = False
ENV = env.str("APPLICATION_ENV", "DEV")
# Host configuration
ALLOWED_HOSTS = ["search.patentsview.org", "localhost"]

# Apps configuration
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]
PV_APPS = [
    "API",
]
THIRD_PARTY_APPS = [
    "social_django",
    "corsheaders",
    "rest_framework",
    "rest_framework_api_key",
    "maintenance_mode",
    "django_celery_results",
    "django_celery_beat",
]
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PV_APPS

# Middleware Configuration
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "maintenance_mode.middleware.MaintenanceModeMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

# URLs & Templates
ROOT_URLCONF = "pvapi.urls"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ],
        },
    },
]

WSGI_APPLICATION = "pvapi.wsgi.application"

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = "/usr/src/app/assets"
STATICFILES_DIRS = [os.path.join(BASE_DIR / "API" / "static")]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "api_backend_cache",
    }
}
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"
        },
        "standard": {
            "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            "datefmt": "%d/%b/%Y %H:%M:%S",
        },
        "simple": {"format": "%(levelname)s %(message)s"},
    },
    "handlers": {
        "logfile": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "django.log"),
            "when": "midnight",
            "interval": 1,
            "backupCount": 7,
            "formatter": "standard",
        },
        "console": {
            "level": "INFO",
            "stream": sys.stdout,
            "class": "logging.StreamHandler",
            "formatter": env.str("LOG_FORMATTER", "standard"),
        },
    },
    "loggers": {
        "django": {
            "handlers": ["logfile", "console"],
            "propagate": False,
            "loglevel": "INFO",
        },
        "API": {
            "handlers": ["logfile", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "root": {
            "handlers": ["logfile", "console"],
            "level": "WARNING",
        },
    },
}
# Authentication
AUTHENTICATION_BACKENDS = (
    "social_core.backends.google.GoogleOAuth2",
    "django.contrib.auth.backends.ModelBackend",
)

# Django Social Auth Configuration
SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
    "social_core.pipeline.social_auth.associate_by_email",
    "social_core.pipeline.debug.debug",
)
USERNAME_IS_FULL_EMAIL = True
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = env.str("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env.str("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET")



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
LOGIN_REDIRECT_URL = "/admin/"

# CORS Settings for public API use
CORS_ALLOW_ALL_ORIGINS = True

REDIS_HOST = env.str("REDIS_HOST")
REDIS_PORT = env.str("REDIS_PORT")
REDIS_DATABASES = {
    "STATS": env.str("REDIS_STATS_DB", "1"),
    "CELERY": env.str("REDIS_CELERY_DB", "2"),
}

MAINTENANCE_MODE = env.bool("PV_MAINTENANCE_MODE", False)

# API Settings
API_KEY_CUSTOM_HEADER = "HTTP_X_API_KEY"
CORS_ALLOW_HEADERS = list(default_headers) + ["x-api-key"]

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "API.permissions.HasUserAPIKey",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": (),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
    "ORDERING_PARAM": "ordering",
    "DEFAULT_THROTTLE_CLASSES": ["API.throttler.APIKeyThrottle"],
    "DEFAULT_THROTTLE_RATES": {"key": "45/m"},
    "EXCEPTION_HANDLER": "API.exceptions.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.openapi.AutoSchema",
}
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"
CELERY_RESULT_EXTENDED = True
CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DATABASES["CELERY"]}'

