# Generated by Django 5.2.17 on 2026-10-06 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("API", "0002_auto_20230912_1555"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=80)),
                ("month", models.CharField(help_text="YYYY-MM, UTC", max_length=7)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "unique_together": {("subject", "month")},
            },
        ),
        migrations.CreateModel(
            name="AccountKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supabase_user_id", models.CharField(db_index=True, max_length=64)),
                ("email", models.EmailField(max_length=254)),
                (
                    "plan",
                    models.CharField(
                        choices=[("free", "Free")], default="free", max_length=32
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rotated_from",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="prefix of the key this one replaced",
                        max_length=16,
                    ),
                ),
                (
                    "api_key",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to="API.apiuserkey",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["supabase_user_id", "plan"],
                        name="lapse_accou_supabas_8c1836_idx",
                    )
                ],
            },
        ),
    ]
