# Generated by Django 5.2.17 on 2026-10-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lapse_accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WindowCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=80)),
                ("win", models.CharField(max_length=40)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "unique_together": {("subject", "win")},
            },
        ),
    ]
